#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pytest-tap
Version  : 3.3
Release  : 20
URL      : https://files.pythonhosted.org/packages/fc/65/df1488188d6a43525460e829ff887cf0330e2c0de6a806765925bdf37d30/pytest-tap-3.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/fc/65/df1488188d6a43525460e829ff887cf0330e2c0de6a806765925bdf37d30/pytest-tap-3.3.tar.gz
Summary  : Test Anything Protocol (TAP) reporting plugin for pytest
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pytest-tap-license = %{version}-%{release}
Requires: pytest-tap-python = %{version}-%{release}
Requires: pytest-tap-python3 = %{version}-%{release}
Requires: pytest
Requires: tap.py
BuildRequires : buildreq-distutils3
BuildRequires : pytest
BuildRequires : tap.py

%description
pytest-tap
==========
|version| |license| |travis| |travismac| |appveyor| |coverage|

%package license
Summary: license components for the pytest-tap package.
Group: Default

%description license
license components for the pytest-tap package.


%package python
Summary: python components for the pytest-tap package.
Group: Default
Requires: pytest-tap-python3 = %{version}-%{release}

%description python
python components for the pytest-tap package.


%package python3
Summary: python3 components for the pytest-tap package.
Group: Default
Requires: python3-core
Provides: pypi(pytest_tap)
Requires: pypi(pytest)
Requires: pypi(tap.py)

%description python3
python3 components for the pytest-tap package.


%prep
%setup -q -n pytest-tap-3.3
cd %{_builddir}/pytest-tap-3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1635810772
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pytest-tap
cp %{_builddir}/pytest-tap-3.3/LICENSE %{buildroot}/usr/share/package-licenses/pytest-tap/8521b76892024fdde6e0ab4b291b133d05d0d074
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pytest-tap/8521b76892024fdde6e0ab4b291b133d05d0d074

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
